export default [
    {
        id: 1,
        name: 'O que são Vacinas?',
        descr: 'A vacina estimula o corpo a se defender contra os organismos (vírus e bactérias) que provocam doenças. As primeiras vacinas foram descobertas há mais de duzentos anos. Atualmente, técnicas modernas são utilizadas para preparar as vacinas em laboratórios. As vacinas podem ser produzidas a partir de organismos enfraquecidos, mortos ou alguns de seus derivados. As vacinas podem ser aplicadas por meio de injeção ou por via oral (pela boca). Quando a pessoa é vacinada, seu corpo detecta a substância da vacina e produz uma defesa, os anticorpos. Esses anticorpos permanecem no organismo e evitam que a doença ocorra no futuro. Isso se chama imunidade.'
    },
    {
        id: 2,
        name: 'Rotina e campanha',
        descr: 'Para que a vacinação seja eficaz, é importante que as pessoas procurem uma sala de vacinação para serem vacinadas, nas idades recomendadas – essa é a chamada vacinação de rotina. Também existem as campanhas de vacinação como, por exemplo, a campanha contra a poliomielite e a campanha do idoso (contra a gripe), que acontecem todo ano. Além de serem vacinadas nas idades recomendadas pelo calendário do Ministério da Saúde, as pessoas também devem receber as vacinas oferecidas nas campanhas de vacinação. Isto é, uma não exclui a outra.'
    },
    {
        id: 3,
        name: 'Muita gente trabalhando por você',
        descr: 'Para que as vacinas cheguem até os postos de saúde e à população, muitas instituições diferentes, dentro e fora do Brasil, e muitas pessoas trabalham juntas durante todo o ano. Lá fora, a Organização Mundial da Saúde (OMS), órgão das Nações Unidas responsável por colaborar com a melhoria da saúde no mundo, apóia os países nas atividades de vacinação. De Brasília, o Ministério da Saúde coordena a vacinação em todo o Brasil, além de ser o responsável pela produção ou compra e distribuição das vacinas utilizadas no Programa Nacional de Imunizações para os vinte e sete estados do país. A Organização Pan-Americana da Saúde (OPAS) auxilia o Ministério da Saúde em várias destas atividades. Nos estados, os governos estaduais se encarregam de distribuir as vacinas pelos municípios, bem como coordenar as atividades de vacinação em todos eles. Por fim, as prefeituras se encarregam de vacinar a população nos postos de saúde. Todos atuam com dedicação para que a população fique protegida contra doenças.'
    },
    {
        id: 4,
        name: 'Vacina contra tuberculose (BCG)',
        descr: 'Vacina: Vacina: BCG, obtida a partir de bactéria viva atenuada.\n\nComo é aplicada?\nPor via intradérmica (injeção sob a pele) de preferência no braço direito. É necessária somente uma dose da vacina e o Ministério da Saúde recomenda uma dose de reforço de seis a dez anos.\n\nQuem deve tomar?\nTodas as crianças.\n\nQuando é preciso tomar a vacina?\nApós o nascimento, na maternidade, em apenas uma dose.\n\nQuais os benefícios da vacina?\nProteção contra as formas graves da tuberculose, doença contagiosa, produzida por bactéria que atinge principalmente os pulmões e que, se não tratada, pode provocar sérios problemas respiratórios, emagrecimento, fraqueza e até levar à morte. A tuberculose é transmitida de pessoa a pessoa pelo ar, por meio de tosse, espirro ou fala. Os principais sintomas são febre ao final do dia, tosse, fraqueza, cansaço e perda de peso.'
    },
    {
        id: 5,
        name: 'Vacina oral contra Poliomielite ou Paralisia Infantil (VOP)',
        descr: 'Vacina: Vacina: VOP, produzida a partir de polivírus vivo atenuado.\n\nComo é aplicada?\nPor via oral. Em três doses, com intervalo de sessenta dias entre cada dose. Cada dose corresponde a duas gotas.\n\nQuem deve tomar?\nTodas as crianças menores de cinco anos, a partir de dois meses de idade.\n\nQuando é preciso tomar?\nAos dois, quatro e seis meses de idade, com reforço aos quinze meses. No Brasil, além disso, todas as crianças menores de cinco anos de idade devem receber a vacina nos dias de Campanha Nacional de Vacinação contra a Poliomielite, independentemente de já estarem com suas vacinas em dia.\n\nQuais os benefícios da vacina?\nProteção contra a poliomielite ou paralisia infantil, doença contagiosa, provocada por vírus e caracterizada por paralisia súbita geralmente nas pernas. A transmissão ocorre pelo contato direto com pessoas ou contato com fezes de pessoas contaminadas, ou ainda contato com água e alimentos contaminados.'
    },
    {
        id: 6,
        name: 'Vacina contra Difteria, Tétano, Coqueluche e Meningite causada por Haemophilus (Vacina Tetravalente)',
        descr: 'Vacina: Combinação da vacina contra difteria, tétano e coqueluche (DTP), feita com bactérias mortas e produtos de bactérias (toxinas), com a vacina contra Haemophilus Influenzae tipo b (Hib), produzida com substâncias da parede da bactéria.\n\nComo é aplicada?\nPor injeção via intramuscular no vasto lateral da coxa (em crianças com menos de dois anos) ou na parte superior do braço – músculo deltóide (em crianças com mais de dois anos). Em três doses, com intervalo de sessenta dias entre cada uma.\n\nQuem deve tomar?\nTodas as crianças.\n\nQuando é preciso tomar?\nAos dois, quatro e seis meses. Aos quinze meses, é necessária uma dose de reforço só com a DTP. A criança deverá receber ainda uma outra dose aos dez ou onze anos com a vacina dupla adulto (difteria e tétano).\n\nQuais os benefícios da vacina?\nProteção contra a difteria, o tétano, a coqueluche e a Haemophilus influenzae do tipo b, que causa um tipo de meningite.\n\nA difteria é causada por um bacilo, produtor de uma toxina difteria(substância tóxica) que atinge as amídalas, a faringe, o nariz e a pele, onde provoca placas branco-acinzentadas. É transmitida, por meio de tosse ou espirro, de uma pessoa contaminada para outra.\nO tétano é uma infecção, causada por uma toxina (substância tóxica) produzida pelo bacilo tetânico, que entra no organismo por meio de ferimentos ou lesões na pele (tétano acidental) ou pelo coto do cordão umbilical (tétano neonatal ou mal dos sete dias) e atinge o sistema nervoso central. Caracteriza-se por contrações e espasmos, dificuldade em engolir e rigidez no pescoço.\nA coqueluche, também conhecida como tosse comprida, coqueluche é uma doença infecciosa, que compromete o aparelho respiratório (traquéia e brônquios) e se caracteriza por ataques de tosse seca. É transmitida por tosse, espirro ou fala de uma pessoa contaminada. Em crianças com menos de seis meses, apresenta-se de forma mais grave e pode levar à morte.\nHaemophilus influenzae do tipo b do tipo b é uma bactéria que do tipo b causa um tipo de meningite (inflamação das meninges, membranas que envolvem o cérebro), sinusite e pneumonia. A doença mais grave é a meningite, que tem início súbito, com febre, dor de cabeça intensa, náusea, vômito e rigidez da nuca (pescoço duro). A meningite é uma doença grave e pode levar à morte.'
    },
    {
        id: 7,
        name: 'Vacina contra Sarampo, Rubéola e Caxumba (Tríplice Viral - SRC)',
        descr: 'Vacina: Vacina: Combinação de vírus vivos atenuados.\n\nComo é aplicada?\nPor injeção via subcutânea (sob a pele). Deve ser aplicada na parte superior do braço – músculo deltóide. É necessária somente uma dose da vacina.\n\nQuem deve tomar?\nTodas as crianças.\n\nQuando é preciso tomar?\nAos doze meses de idade e nos momentos em que ocorrerem as campanhas de seguimento para vacinação contra o sarampo.\n\nQuais os benefícios da vacina?\nProteção contra o sarampo, a rubéola e a caxumba.\n\nO sarampo sarampo é uma doença muito contagiosa, causada sarampo por um vírus que provoca febre alta, tosse, coriza e manchas avermelhadas pelo corpo. É transmitida de pessoa a pessoa por tosse, espirro ou fala especialmente em ambientes fechados. Facilita o aparecimento de doenças como a pneumonia e diarréias e pode levar à morte, principalmente em crianças pequenas.\n\nA rubéola é uma doença muito contagiosa, provocada por rubéola um vírus que atinge principalmente crianças e provoca febre e manchas vermelhas na pele, começando pelo rosto, couro cabeludo e pescoço e se espalhando pelo tronco, braços e pernas. É transmitida pelo contato direto com pessoas contaminadas.\n\nA caxumba é uma doença viral, caracterizada por febre caxumba e aumento de volume de uma ou mais glândulas responsáveis pela produção de saliva na boca (parótida) e, às vezes, de glândulas que ficam sob a língua ou a mandíbula (sub-linguais e sub-mandibulares). O maior perigo é a caxumba “descer”, isto é, causar inflamação dos testículos principalmente em homens adultos, que podem ficar sem poder ter filhos depois da infecção. Pode causar ainda inflamação dos ovários nas mulheres e meningite viral. É transmitida pela tosse, espirro ou fala de pessoas infectadas.'
    },
    {
        id: 8,
        name: 'Vacina contra Hepatite B',
        descr: 'Vacina: Vacina: Obtida por técnicas de engenharia genética, a partir de componentes do vírus da Hepatite B.\n\nComo é aplicada?\nPor injeção via intramuscular no vasto lateral da coxa (em crianças com menos de dois anos) ou na parte superior do braço – músculo deltóide (em crianças com mais de dois anos). São necessárias três doses da vacina: a primeira logo após o nascimento, a segunda trinta dias após a primeira, a terceira seis meses após a primeira.\n\nQuem deve tomar?\nTodas as crianças.\n\nQuando é preciso tomar a vacina?\nA primeira dose, ainda na maternidade. A segunda dose, com um mês de idade. A terceira dose, com seis meses.\n\nQuais os benefícios da vacina?\nProteção contra Hepatite B, doença causada por um vírus e que provoca mal-estar, febre baixa, dor de cabeça, fadiga, dor abdominal, náuseas, vômitos e aversão a alguns alimentos. O doente fica com a pele amarelada. A Hepatite B é grave, porque pode levar a uma infecção crônica (permanente) do fígado e, na idade adulta, levar ao câncer de fígado.'
    },
    {
        id: 9,
        name: 'Vacina contra Febre Amarela',
        descr: 'Vacina: Vacina: Constituída de vírus vivos atenuados.\n\nComo é aplicada?\nPor injeção via subcutânea (sob a pele) na parte superior do braço – músculo deltóide. Uma dose, com reforço a cada dez anos.\n\nQuem deve tomar?\nCrianças, a partir dos seis meses de idade, em regiões endêmicas (onde há casos da doença em humanos).Em regiões onde há circulação do vírus entre animais (macacos), mas não em humanos, a vacina deve ser dada aos nove meses de idade. A vacina deve ser dada ainda a todas as pessoas que pretenderem viajar para locais onde a febre amarela é endêmica.\n\nQuando é preciso tomar?\nAos seis ou aos nove meses, dependendo da região. Os adultos podem tomar em qualquer idade. A vacina protege o organismo por apenas dez anos. Portanto, é necessário tomar uma nova dose da vacina a cada dez anos.\n\nQuais os benefícios da vacina?\nProteção contra a febre amarela, doença infecciosa, causada por um vírus transmitido por vários tipos de mosquito. O Aedes aegypti pode transmitir a febre amarela, causando a febre amarela urbana, o que, desde 1942, não ocorre no Brasil. A forma da doença que ocorre no Brasil é a febre amarela silvestre, que é transmitida pelos mosquitos Haemagogus e o Sabethes, em regiões fora das cidades. É uma doença grave, que se caracteriza por febre repentina, calafrios, dor de cabeça, náuseas e leva a sangramento no fígado, no cérebro e nos rins, podendo, em muitos casos, causar a morte.'
    },
    {
        id: 10,
        name: 'Vacina contra Difteria e Tétano (Dupla Adulto - dT)',
        descr: 'Vacina: Vacina: dT, fabricada com produtos de bactérias (toxinas).\n\nComo é aplicada?\n Por injeção via intramuscular na parte superior do braço – músculo deltóide – ou no vasto lateral da coxa. Adolescentes não vacinados devem tomar três doses (com intervalo de dois meses entre as doses (zero, dois, quatro meses)). Adolescentes que já receberam a vacina DTP na infância devem tomar uma dose de reforço a cada dez anos.\n\nQuem deve tomar?\nTodos os adolescentes.\n\nQuando é preciso tomar?\nAdolescentes que nunca tomaram a vacina podem tomar em qualquer idade. Quem recebeu uma dose de dupla adulto aos dez ou onze anos precisa receber apenas um reforço a cada dez anos. Quem tomou a última dose há mais de dez anos precisa tomar uma dose de reforço e não esquecer que, para fazer efeito por toda a vida, são necessárias doses de reforço da vacina a cada dez anos.\n\nQuais os benefícios da vacina?\nProteção contra o tétano e a difteria. A difteria difteria é causada por um bacilo, produtor de uma toxina difteria (substância tóxica) que atinge as amídalas, a faringe, o nariz e a pele, onde provoca placas branco-acinzentadas. É transmitida, por meio de tosse ou espirro, de uma pessoa contaminada para outra.\n\O tétano é uma infecção, causada por uma toxina (substância tóxica) tétano produzida pelo bacilo tetânico, que entra no organismo por meio de ferimentos ou lesões na pele (tétano acidental) ou pelo coto do cordão umbilical (tétano neonatal ou mal dos sete dias) e atinge o sistema nervoso central. Caracteriza-se por contrações e espasmos, dificuldade em engolir e rigidez no pescoço.'
    },
    {
        id: 11,
        name: 'Vacina contra Gripe (Influenza)',
        descr: 'Vacina: Vacina: Composta por vírus mortos. Por ser um vírus que muda muito (mutante), a cada ano, uma nova vacina é desenvolvida, pois são levados em consideração os tipos de vírus que estão circulando no momento. A Organização Mundial da Saúde (OMS) recomenda, a cada ano, quais tipos de vírus que devem ser utilizados para fazer a vacina.\n\nComo é aplicada?\nPor injeção via intramuscular na parte superior do braço – músculo deltóide. Uma dose por ano.\n\nQuem deve tomar?\nPessoas com mais de sessenta anos.\n\nQuando é preciso tomar?\nUma vez por ano, no outono (abril/maio), quando acontece a campanha nacional de vacinação do idoso.\n\nQuais os benefícios da vacina?\nProteção contra a influenza ou gripe, doença caracterizada por febre alta, calafrios, dor-de-cabeça, mal-estar, tosse seca e dor muscular, e que pode gerar complicações como infecções respiratórias agudas. Estudos recentes indicam que a vacina também protege contra infarto e derrame. A vacina contra gripe não protege contra resfriados comuns, que são causados por outros tipos de vírus e normalmente se caracterizam por sintomas mais leves, sem febre.'
    },
    {
        id: 12,
        name: 'Vacina contra Pneumonia (Pneumococo)',
        descr: 'Vacina: Vacina: Obtida a partir de substância purificada da bactéria causadora da pneumonia.\n\nComo é aplicada?\nPor injeção via intramuscular ou subcutânea na parte superior do braço. Em dose única, e precisa de uma dose de reforço cinco anos após a primeira dose .\n\nQuem deve tomar?\nPessoas com mais de sessenta anos que vivem em instituições fechadas como asilos, hospitais e casas de repouso, por apresentarem mais riscos de contrair pneumonias.\n\nQuando é preciso tomar?\nDurante as campanhas de vacinação destinadas aos idosos, em abril/maio. Lembrar que é preciso uma única dose de reforço cinco anos após a primeira dose.\n\nQuais os benefícios da vacina?\nProteção contra a pneumonia causada pelo pneumococo. A pneumonia é uma infecção respiratória grave, que se caracteriza por febre, tosse com catarro, e, em muitos casos, precisa de internação, podendo levar a pessoa à morte, se não tratada adequadamente.'
    },
    {
        id: 13,
        name: 'As vacinas provocam reações?',
        descr: 'Após receberem as vacinas, as pessoas podem sentir algumas reações que são esperadas como febre, cansaço, dor e vermelhidão local. Isto ocorre pois a vacina está estimulando a produção dos anticorpos e a defesa do nosso organismo.\n\nEstas reações são geralmente transitórias e não fazem mal, apesar de serem incômodas.'
    },
    
];